sudo: required

services:
  - docker

matrix:
  include:
    - os: linux

before_install:
  - docker pull ponylang/ponyc

script:
  - docker run -v ${$TRAVIS_BUILD_DIR}:/src/main ponylang/ponyc ./main
